cart/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views


urlpatterns = [

    # url(r'^adicionar/(?P<product_slug>[-\w]+)/$', views.adicionar_carrinho, name="adicionar_carrinho"),
    url(r'^update/$', views.update_cart, name="update_cart"),
    url(r'^add/$', views.add_cart, name="add_cart"),
    url(r'^$', views.show_cart, name="show_cart"),
    #url(r'^cart/delete/(?P<pk>\d+)/$', views.ItemDelete.as_view(), name='cart_item_delete'),
    url(r'^cart/deleteall/$', views.delete_all_items, name='cart_delete_allitems'),
    url(r'^cart/delete/(?P<pk>\d+)/$', views.delete_item, name='cart_item_delete'),


]

myshop/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [

    url(r'^admin/', include(admin.site.urls)),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^', include('shop.urls', namespace='shop')),

    #url(r'^', include('registration.backends.simple.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^create/$', views.order_create, name='order_create'),
]

shop/urls.py
from django.conf.urls import url
from django.contrib import admin
#from django.contrib.auth import views as auth_views
from . import views


from django.contrib.auth.views import (
    password_change,
    password_change_done,
)

urlpatterns = [

    # edit user profile
    url(r'^edit/$', views.edit, name='edit'),

    # user registration
    url(r'^register/$', views.register, name='register'),

    # restore password urls
    url(r'^password-reset/$',
        'django.contrib.auth.views.password_reset',
        {'post_reset_redirect': 'shop:password_reset_done'},
        name='password_reset'),

    url(r'^password-reset/done/$','django.contrib.auth.views.password_reset_done', name='password_reset_done'),

    url(r'^password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$',
        'django.contrib.auth.views.password_reset_confirm',
        {'post_reset_redirect': 'shop:password_reset_complete'},
        name='password_reset_confirm'),

    url(r'^password-reset/complete/$', 'django.contrib.auth.views.password_reset_complete', name='password_reset_complete'),

    url(r'^password-change/$',
        'django.contrib.auth.views.password_change',
        { 'post_change_redirect': 'shop:password_change_done'},
        name='password_change'),
    url(r'^password-change/done/$', 'django.contrib.auth.views.password_change_done', name='password_change_done'),


    # para login
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    url(r'^login/$', 'django.contrib.auth.views.login', name='login'),
    url(r'^loggedout/$', 'django.contrib.auth.views.logout', name='loggedout'),
    url(r'^logout-then-login/$', 'django.contrib.auth.views.logout_then_login', name='logout_then_login'),

    # show orders list
    url(r'^orderlist/$', views.order_list, name='order_list'),

    # products
    url(r'^product/(?P<product_slug>[-\w]+)/$', views.product_details, name='product_details'),
    url(r'^$', views.product_list, name="product_list"),
    url(r'^(?P<sub_category_slug>[-\w]+)/$', views.product_list, name='product_list_by_subcategory'),



]

cart/models.py
from django.contrib.auth.models import User
from django.db import models

from shop.models import Product


class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    total = models.DecimalField(default=0.00, max_digits=10, decimal_places=2)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def get_total_items(self):
        total = 0
        return total

    def __str__(self):
        return str(self.id)

    def total_value_cart(self):
        result = sum(items.product.price * items.quantity for items in self.item_set.all())
        self.total = result


class Item(models.Model):

    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, null=True)
    quantity = models.PositiveIntegerField()

    # not allowing duplicates of the same Item in the same Cart
    class Meta:
        unique_together = ('product', 'cart')

    def __str__(self):
        return self.product.name

    def get_total_price(self):
        return self.product.price * self.quantity

cart/views.py
#global imports
from django.core.exceptions import ObjectDoesNotExist
from django.core.urlresolvers import reverse
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.views.generic import DeleteView


#local imports
from shop.models import Product
from .models import Cart, Item


# class ItemDelete(DeleteView):
#     model = Item
#     success_url = '/cart'
    #pk_url_kwarg = "id"

def delete_item(request, pk):
    try:

        item = Item.objects.get(id=pk)
        item.delete()

        user = request.user
        cart = Cart.objects.filter(user=user).last()
        items = Item.objects.filter(cart=cart)
        total = sum(i.product.price * i.quantity for i in items)
        cart.total = total
        cart.save()

    except ObjectDoesNotExist:
        return HttpResponseRedirect(reverse("cart:show_cart"))
    return HttpResponseRedirect(reverse("cart:show_cart"))


def delete_all_items(request):
    try:

        item = Item.objects.all()
        item.delete()

        user = request.user
        cart = Cart.objects.filter(user=user).last()
        items = Item.objects.filter(cart=cart)
        total = sum(i.product.price * i.quantity for i in items)
        cart.total = total
        cart.save()

    except ObjectDoesNotExist:
        return HttpResponseRedirect(reverse("cart:show_cart"))
    return HttpResponseRedirect(reverse("cart:show_cart"))


def add_cart(request):
    slug = request.POST.get('slug', '')
    quantity = request.POST.get("quantity", "")

    if request.method == 'POST':
        product = get_object_or_404(Product, slug=slug)

        if quantity == '':
            return render(request, 'shop/product/details.html', {'product': product, 'stock_error': 1})
        elif int(quantity) < 1 or product.stock < int(quantity):
            return render(request, 'shop/product/details.html', {'product': product, 'stock_error': 1})

        # Pesquisar por user
        user = request.user

        # ***** Filter cart by user, if it doesnt exist create
        if Cart.objects.filter(user=user):
            cart = Cart.objects.filter(user=user).last()
        else:
            cart = Cart(user = user)
            cart.save()


        # Com o cart verificar se existem o item dentro do cart
        # se existir aumenta a quantity
        # cc Cria o item e adiciona ao cart
        item_repeated = Item.objects.filter(cart=cart, product=product).first()
        if not item_repeated:
            # Criar novo Item
            item = Item(
                product=product,
                quantity=quantity,
                cart=cart
            )
            item.save()
        else:
            # Update Item
            item_repeated.quantity += int(quantity)
            item_repeated.save()
            # return render(request, 'cart/cart.html')

        items = Item.objects.filter(cart=cart)
        total = sum(i.product.price * i.quantity for i in items)
        cart.total = total
        cart.save()

        return show_cart(request)

        # return render(request, 'cart/cart.html', {'product': product})


def show_cart(request):

    user = request.user

    # ***** Filter cart by user, if it doesnt exist create
    if Cart.objects.filter(user=user):
        cart = Cart.objects.filter(user=user).last()
    else:
        cart = Cart(user=user)
        cart.save()

    #items = Item.objects.filter(cart = cart).select_related('product')
    items = Item.objects.filter(cart=cart)

    # total = sum(i.product.price*i.quantity for i in items)
    total = cart.total

    #item = Item.objects.filter(item=id_produto).first()

    return render(request, 'cart/cart.html', {'items': items, 'total': total, })


def update_cart(request):
    slug = request.POST.get('slug', '')
    quantity = request.POST.get("quantity", "")
    # slug = request.GET.get('slug')
    # quantity = request.GET.get("quantity")
    stock_error = 0
    items = None
    total = 0

    if request.method == 'POST':
        product = get_object_or_404(Product, slug=slug)

        # Pesquisar por user
        user = request.user

        # ***** Filter cart by user, if it doesnt exist create
        if Cart.objects.filter(user=user):
            cart = Cart.objects.filter(user=user).last()
        else:
            cart = Cart(user= user)
            cart.save()

        items = Item.objects.filter(cart=cart)
        item_repeated = Item.objects.filter(cart=cart, product=product).first()

        # Update Item
        if product.stock >= int(quantity) and int(quantity)>0:
            item_repeated.quantity = int(quantity)
            item_repeated.save()

            total = sum(i.product.price * i.quantity for i in items)
            cart.total = total
            cart.save()

            stock_error = 0

            # answer = ""
            # data = {
            #     'respond': answer,
            #     'quantity': quantity,
            # }
            # return JsonResponse(data)
        else:
            stock_error = 1
            total = cart.total
            # answer = "Valor Superior ao Stock Existente"
            # data = {
            #     'respond': answer,
            #     'quantity': quantity,
            # }
            # return JsonResponse(data)

    return render(request, 'cart/cart.html', {'items': items, 'total': total, 'stock_error': stock_error})

cart/templates/cart/cart.html
{% extends "shop/base.html" %}
{% load static %}

{% block content %}
    {% if stock_error == 1 %}
        <span style="color: red; float:left" id="alert_quantity">
            <script>
                alert("Erro na selecção de quantidade (quantidade > 0 e quantidade <= stock)")
            </script>
        </span>
    {% endif %}
    <h1>Carrinho</h1>
    <table class="cart">
        <thead>
        <tr>
            <th>Image</th>
            <th>Product</th>
            <th>Quantity</th>
            <th>Remove</th>
            <th>Unit price</th>
            <th>Price</th>
        </tr>
        </thead>
        <tbody>
            {% for i in items %}
                <tr>
                    <td>
                        <a href="{{ i.product.get_absolute_url }}">
                            <img src="{% if i.product.image %}{{ i.product.image.url}}{% else %}{% static "shop/img/no_image.png" %}{% endif %}">
                        </a>
                    </td>
                    <td>{{ i.product.name }}</td>
                    <td>
                        <form id='updateform' action='{% url "cart:update_cart" %}' method="post">
                            {% csrf_token %}
                            <input style="width:10%" type="number" name="quantity" value="{{ i.quantity }}" id="product_quantity"/>
                            <input type="hidden" value="{{ i.product.name }}" id="product_name"/>
                            <input type="hidden" name="slug" value="{{ i.product.slug }}" id="product_slug"/>
                            <input type="submit" value="Update" />
                        </form>

                    </td>


{#                    <td id="quantity_ajax">{{ i.quantity }}</td>#}

                    <td><a href="{% url "cart:cart_item_delete" i.id%}">Remove</a></td>
                    <td id="product_price">{{ i.product.price }}</td>
                    <td id="total_price">{{ i.get_total_price }}</td>

                </tr>
            {% endfor %}
            <tr>
                <td></td><td></td><td></td><td></td><td>Total: </td><td>{{ total }}</td>
            </tr>




        </tbody>

    </table>


    <p class="text-right">

        {# If total its zero, the button "Esvaziar Carrinho" and "Finalizar Compra" doesnt appear #}
        {% if total != 0 %}
            {% if stock_error == 1 %}

            {% else %}
                <a href="{% url "cart:cart_delete_allitems" %}" class="button light">Esvaziar Carrinho</a>
                <a href="{% url "orders:order_create" %}" class="button">Finalizar Compra</a>
            {% endif %}
        {% endif %}

        <a href="{% url "shop:product_list" %}" class="button light">Comprar mais!</a>

    </p>

{#    <script>#}
{#            $(document).ready(function(){#}
{#                $("#updateform").on('submit', function (e) {#}
{#                        e.preventDefault();#}
{#                        var quantity = $("#produto_quantity").val();#}
{#                        var name = $("#produto_nome").val();#}
{#                        var slug = $("#produto_slug").val();#}
{#                        //var input = $(this).serialize()#}
{##}
{#                        $.ajax({#}
{#                            url: '{% url 'cart:atualizar_carrinho' %}',#}
{#                            data: {#}
{#                              'quantity': quantity,#}
{#                                'name': name,#}
{#                                'slug':slug,#}
{#                            },#}
{#                            dataType: 'json',#}
{#                            success: function (data) {#}
{#                              document.getElementById('alert_quantity').innerHTML = data['respond'];#}
{#                              document.getElementById('quantidade_ajax').innerHTML = data['quantity'];#}
{##}
{#                            }#}
{#                          });#}
{#                        });#}
{#            })#}
{#    </script>#}

{% endblock %}